### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by TunedMystic** [sjbitcode/daca-news#3]
Decide on a db for the project _(sqlite or postgres)_

Mock up table schemas that we might need to use.

<br />

Maybe something like:
```python
Article  # content that is pulled from news sources
  - title (char)
  - url (char)
  - category (fk?)
  - created_at (datetime)

Digest  # email that is sent. Can reference many articles
  - sent_at (datetime)

Recipient  # a user that receives the email digest.
  - name (char)
  - email (char)
```

**Comment by sjbitcode** [comment]
Done! 🎉  

We might need to tweak the tables as we go along, here are all the tables so far:
- `articles`
- `digest`
- `recipient`
- `articles_digest` -> (through table for articles <-> digest many-to-many relationship)
- `articles_recipient` -> (through table for articles <-> recipient many-to-many relationship)
